
#服务端口
server:
  port: 8882

eureka:
  instance:
    hostname: register-salve2
  client:
    #通过设置fetch-registry与register-with-eureka 表明自己是一个eureka服务
    fetch-registry: false
#    register-with-eureka: false
    #注册register-salve1，register-salve2做注册中心集群
    service-url:
      defaultZone: http://register-master:8880/eureka/,http://register-salve1:8881/eureka/

spring:
  application:
    name: register-center

management:
  security:
    enabled: false