#---
#server:
#  port: 8885
#spring:
#  profiles: dev
#  application:
#    name: user-service
#  #redis集群配置
#  redis:
#    cluster:
#      #多节点
#      nodes:
#        - 192.168.2.222:7000
#        - 192.168.2.222:7001
#        - 192.168.2.222:7002
#        - 192.168.2.222:7003
#        - 192.168.2.222:7004
#        - 192.168.2.222:7005
#      #跨群集执行命令时要遵循的最大重定向数
#      max-redirects: 2
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0
#     连接超时时间（毫秒）
#    timeout: 5000
#
#  data:
#    mongodb:
#      custom:
#        hosts: localhost
#        ports: 27017
#        database: test
#        authentication-database: local
#        replica-set: mgset-3590061
#        connections-per-host: 20
#        min-connections-per-host: 10
#
#eureka:
#  instance:
#    status-page-url: http://localhost:${server.port}/swagger-ui.html
#  client:
#    service-url:
#      defaultZone: http://register-master:8880/eureka/
#
#feign:
#  hystrix:
#    enabled: true






