eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://register-master:8880/eureka/

server:
  port: 8884

spring:
  application:
    name: service-zuul



zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: user-service
    api-b:
      path: /api-b/**
      serviceId: dept-service
  host:
  #设置请求分发的超时时间
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

#启动feign熔断器功能
feign:
  hystrix:
    enabled: true
