
#服务端口
server:
  port: 8881

eureka:
  instance:
    hostname: register-salve1
  client:
    #通过设置fetch-registry与register-with-eureka 表明自己是一个eureka服务

#    #由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    fetch-registry: false
#    #默认设置下，服务注册中心也会将自己作为客户端来尝试注册自己，这里禁用它的客户端注册行为
#    register-with-eureka: false
    #注册register-salve1，register-salve2做注册中心集群
    service-url:
      defaultZone: http://register-master:8880/eureka/,http://register-salve2:8882/eureka/

spring:
  application:
    name: register-center


management:
  security:
    enabled: false